version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=olusholaayoade@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    environment:
      PORT: 80
      AUTH_API_ADDRESS: http://auth-api:8081
      TODOS_API_ADDRESS: http://todos-api:8082
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`autobud.co`) || Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    depends_on:
      - auth-api
    networks:
      - app-network

  auth-api:
    build:
      context: ./auth-api
    environment:
      AUTH_API_PORT: 8081
      JWT_SECRET: myfancysecret
      USERS_API_ADDRESS: http://users-api:8083
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-api.rule=Host(`autobud.co`) && PathPrefix(`/login`)"
      - "traefik.http.routers.auth-api.entrypoints=websecure"
      - "traefik.http.routers.auth-api.tls.certresolver=myresolver"
      - "traefik.http.services.auth-api.loadbalancer.server.port=8081"
    depends_on:
      - redis
    networks:
      - app-network

  todos-api:
    build:
      context: ./todos-api
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: myfancysecret
      TODO_API_PORT: 8082
      REDIS_CHANNEL: log_channel
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todos-api.rule=Host(`autobud.co`) && PathPrefix(`/todos`)"
      - "traefik.http.routers.todos-api.entrypoints=websecure"
      - "traefik.http.routers.todos-api.tls.certresolver=myresolver"
      - "traefik.http.services.todos-api.loadbalancer.server.port=8082"
    depends_on:
      - redis
    networks:
      - app-network

  log-message-processor:
    build:
      context: ./log-message-processor
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CHANNEL: log_channel
      ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
    labels:
      - "traefik.enable=false"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  zipkin:
    image: "openzipkin/zipkin"
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network

  users-api:
    build:
      context: ./users-api
    environment:
      JWT_SECRET: myfancysecret
      SERVER_PORT: 8083
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-api.rule=Host(`autobud.co`) && PathPrefix(`/users`)"
      - "traefik.http.routers.users-api.entrypoints=websecure"
      - "traefik.http.routers.users-api.tls.certresolver=myresolver"
      - "traefik.http.services.users-api.loadbalancer.server.port=8083"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

